### ISSUE TITLE
Need Guidance!! 

### ISSUE THREAD

**Issue by AkshayDube11** [kelvnt/DataAnonymizer#1]
Hi, 

I want to know more about adding regex logic to additionally hash sensitive data using NER_anonymizer. I tried adding a hash regex logic for masking the email addresses but it's not working. Can you please help me with the same and let me know what I am doing wrongly. 

My code snippet: (I have no categorical column in my dataset).

**anonymized_df, hash_dictionary = anonymizer.anonymize(
    free_text_columns=["Sentences"],
    free_text_additional_regex_to_hash={
        "Sentences": ["\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,5}\b"] # regex for email addresses
        },
    pretrained_model_name="dslim/bert-base-NER",
    labels_to_anonymize=["B-PER", "I-PER", "B-LOC", "I-LOC"]
)**

**Comment by kelvnt** [comment]
Hi Akshay,

Thanks for using this package. Do check if I'm wrong but this is actually not an issue related to the implementation of the anonymizer, but rather how you have specified your regex. The way it is currently written only looks for email addresses that are all capitalized. You may want to try the following regex pattern instead:

`\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,5}\b`

You may test out your regex patterns at https://regexr.com/

**Comment by AkshayDube11** [comment]
Dear Kelvin,

Thank you so much for helping me with the correction. I have tried using multiple regex logic to get the email IDs hashed but It's not working. can you suggest any changes I should make in my code mentioned above to get the mail IDs along with NER(PER, LOC) only to be hashed?

**Comment by AkshayDube11** [comment]
Also, can I put multiple regexes in "free_text_additional_regex_to_hash" segment. If yes, how? 
As I also tried to put a regex for PHone numbers alongside email ID, which also did'nt resulted well!

**Comment by kelvnt** [comment]
I am able to pick up email addresses with the regex I just provided you. Have you tried it with that regex? You may add multiple regexes as another in the list:

```
free_text_additional_regex_to_hash={
        "page_content": ["regex_1", "regex_2", ...]
    }
```

You will need to ensure that your regex is able to pick up the patterns (phone numbers / email addresses) that you want. Do check it at the website I provided earlier.

**Comment by AkshayDube11** [comment]
Yes, I tried with the regex you provided. But the email IDs I have in my free text are not getting picked up. Should I go for the multilingual NER model as my free text have some german sentences as well. If yes, then which multilingual model should I go for considering my objective of hashing emails, phone numbers, and NER(PER, LOC) from my text.

Changes suggested in the code:

anonymized_df, hash_dictionary = anonymizer.anonymize(
  free_text_columns=["Sentences"],
  free_text_additional_regex_to_hash={
    "Sentences": ["\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+.[A-Za-z]{2,5}\b"] # for email addresses
    },
  pretrained_model_name="dslim/bert-base-NER",
  labels_to_anonymize=["B-PER", "I-PER", "B-LOC", "I-LOC"]
)

**Comment by kelvnt** [comment]
The choice of the NER model will only affect how well it is able to identify certain named entities that you may want to anonymize. I will not be able to advise you on this as I do not have access to your data; you should probably go through an iterative process with your data and the NER model to determine if it the model suits your purposes.

The regex portion was included to allow flexibility in picking up particular word patterns that might be missed by the selected NER model, including but not limited to email addresses, phone numbers, etc. To test whether your regex works, get a few examples of text containing the words that you want to pick up with regex and try it out at https://regexr.com/ 
I am unable to advice any further on the regex pattern as it all depends on your data and what you're trying to pick out - e.g. phone numbers have different lengths in different countries, and will hence require different regex patterns to pick up depending on context

**Comment by AkshayDube11** [comment]
Thank you so much, Kevin!

It was a very helpful conversation. As suggested, I am onto try out different regex as per my need with the code I have. Also, I trying to figure out a Multilingual model to go for as per my objective from the list on (https://huggingface.co/models). If you have any suggestions for such a multilingual NER_anonymizer-based model, please help me with a few of their names. So that I can try them.

Have a wonderful day ahead!
